name: CI

on: [push, pull_request]

jobs:

  # Ensure code is properly formatted
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
        override: true
        profile: minimal
    - name: Check library formatting
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --verbose -- --check
  
  # Lint the library
  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        override: true
        profile: minimal
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --verbose -- -D warnings
        name: Lint the library
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --verbose --features=edma34 -- -D warnings
        name: Lint the library with eDMA34

  # Run tests
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run unit and documentation tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - uses: actions/checkout@v2
    - name: Run unit and documentation tests for eDMA3/4
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose --features=edma34

  # Make sure documentation builds, and doclinks are valid
  doc:
    env:
      RUSTDOCFLAGS: -D warnings
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check documentation and doclinks
      uses: actions-rs/cargo@v1
      with:
        command: rustdoc
